### ISSUE TITLE
Infografia_Kevin Osorio

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/infografia-de-hilos-Kevinosorio77#2]
[Infogía _kevin.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Kevinosorio77/files/15098944/Infogia._kevin.pdf)

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica de evaluacion obtuviste un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
